requirejs.config {
	baseUrl: '/js',
	paths:
		'jquery'                         : 'vendor/jquery/jquery-2.0.0'
		'underscore'                     : 'vendor/underscore'
		'three'                          : 'vendor/three/three'
		'detector'                       : 'vendor/three/detector'
		'csg'                            : 'vendor/three/csg'
		'bsp'                            : 'vendor/three/bsp'
		'dragpan-controls'               : 'vendor/three/x/dragpan-controls'
		'trackball'                      : 'vendor/three/x/trackball'
		'domevent'                       : 'vendor/three/x/domevent'
		'gl-capability'                  : 'vendor/three/x/gl-capability'
		'window-resize'                  : 'vendor/three/x/window-resize'
		'full-screen'                    : 'vendor/three/x/full-screen'
		'vector3'                        : 'vendor/three/vector'
		'quaternion'                     : 'vendor/three/quaternion'
		'object3d'                       : 'vendor/three/object3d'
		'matrix4'                        : 'vendor/three/matrix4'
		'matrix3'                        : 'vendor/three/matrix3'
		'projector'                      : 'vendor/three/projector'
		'vector4'                        : 'vendor/three/vector4'
		'vector2'                        : 'vendor/three/vector2'
		'box3'                           : 'vendor/three/box3'
		'frustum'                        : 'vendor/three/frustum'
		'plane'                          : 'vendor/three/plane'
		'color'                          : 'vendor/three/color'
		'texture'                        : 'vendor/three/texture'
		'event-dispatcher'               : 'vendor/three/event-dispatcher'
		'webglshaders'                   : 'vendor/three/webglshaders'
		'webglrenderer'                  : 'vendor/three/webglrenderer'
		'sprite-plugin'                  : 'vendor/three/sprite-plugin'
		'shadowmap-plugin'               : 'vendor/three/shadowmap-plugin'
		'lensflare-plugin'               : 'vendor/three/lensflare-plugin'
		'material'                       : 'vendor/three/material'
		'shader-material'                : 'vendor/three/shader-material'
		'shader-sprite'                : 'vendor/three/shader-sprite'
		'shader-flares': 'vendor/three/shader-flares'
		'scene': 'vendor/three/scene'
}

require ['app']