requirejs.config {
	baseUrl: '/js',
	paths:
		'jquery'                         : 'vendor/jquery/jquery-2.0.0'
		'underscore'                     : 'vendor/underscore'
		'leap'                           : 'vendor/leap'

		'bone'                           : 'vendor/three/bone'
		'fogexp2'                        : 'vendor/three/fogexp2'
		'box3'                           : 'vendor/three/box3'
		'bsp'                            : 'vendor/three/bsp'
		'camera'                         : 'vendor/three/camera'
		'color'                          : 'vendor/three/color'
		'csg'                            : 'vendor/three/csg'
		'detector'                       : 'vendor/three/detector'
		'domevent'                       : 'vendor/three/x/domevent'
		'event-dispatcher'               : 'vendor/three/event-dispatcher'
		'frustum'                        : 'vendor/three/frustum'
		'full-screen'                    : 'vendor/three/x/full-screen'
		'geometry'                       : 'vendor/three/geometry'
		'gl-capability'                  : 'vendor/three/x/gl-capability'
		'image-loader'                   : 'vendor/three/image-loader'
		'image-utils'                    : 'vendor/three/image-utils'
		'lensflare-plugin'               : 'vendor/three/lensflare-plugin'
		'light'                          : 'vendor/three/light'
		'line'                           : 'vendor/three/line'
		'event-target'                   : 'vendor/three/event-target'
		'line-basic-material'            : 'vendor/three/line-basic-material'
		'line-dashed-material'           : 'vendor/three/line-dashed-material'
		'material'                       : 'vendor/three/material'
		'math'                           : 'vendor/three/math'
		'matrix3'                        : 'vendor/three/matrix3'
		'matrix4'                        : 'vendor/three/matrix4'
		'object3d'                       : 'vendor/three/object3d'
		'perspective-camera'             : 'vendor/three/perspective-camera'
		'plane'                          : 'vendor/three/plane'
		'projector'                      : 'vendor/three/projector'
		'quaternion'                     : 'vendor/three/quaternion'
		'scene'                          : 'vendor/three/scene'
		'shader-flares'                  : 'vendor/three/shader-flares'
		'shader-material'                : 'vendor/three/shader-material'
		'shader-sprite'                  : 'vendor/three/shader-sprite'
		'shader-chunk'                   : 'vendor/three/shader-chunk'
		'shader-utils'                   : 'vendor/three/shader-utils'
		'shader-lib'                     : 'vendor/three/shader-lib'
		'uniforms-utils'                 : 'vendor/three/uniforms-utils'
		'uniforms-lib'                   : 'vendor/three/uniforms-lib'
		'shadowmap-plugin'               : 'vendor/three/shadowmap-plugin'
		'sphere'                         : 'vendor/three/sphere'
		'sprite'                         : 'vendor/three/sprite'
		'particle-system'                : 'vendor/three/particle-system'
		'particle-basic-material'        : 'vendor/three/particle-basic-material'
		'sprite-material'                : 'vendor/three/sprite-material'
		'sprite-plugin'                  : 'vendor/three/sprite-plugin'
		'texture'                        : 'vendor/three/texture'
		'three'                          : 'vendor/three/three'
		'ribbon'                         : 'vendor/three/ribbon'
		'buffer-geometry'                : 'vendor/three/buffer-geometry'
		'skinned-mesh'                   : 'vendor/three/skinned-mesh'
		'mesh'                           : 'vendor/three/mesh'
		'data-texture'                   : 'vendor/three/data-texture'
		'compressed-texture'             : 'vendor/three/compressed-texture'
		'mesh-basic-material'            : 'vendor/three/mesh-basic-material'
		'cube-geometry'                  : 'vendor/three/cube-geometry'
		'face3'                          : 'vendor/three/face3'
		'face4'                          : 'vendor/three/face4'
		'lens-flare'                     : 'vendor/three/lens-flare'
		'mesh-face-material'             : 'vendor/three/mesh-face-material'
		'mesh-depth-material'            : 'vendor/three/mesh-depth-material'
		'mesh-lamber-material'            : 'vendor/three/mesh-lamber-material'
		'mesh-normal-material'           : 'vendor/three/mesh-normal-material'
		'mesh-phong-material'           : 'vendor/three/mesh-phong-material'
		'webglrender-target'             : 'vendor/three/webglrender-target'
		'webglrender-target-cube'        : 'vendor/three/webglrender-target-cube'
		'trackball'                      : 'vendor/three/x/trackball'
		'vector2'                        : 'vendor/three/vector2'
		'vector3'                        : 'vendor/three/vector3'
		'vector4'                        : 'vendor/three/vector4'
		'webglrenderer'                  : 'vendor/three/webglrenderer'
		'window-resize'                  : 'vendor/three/x/window-resize'

		'immediate-render-object'        : 'vendor/three/immediate-render-object'

}

require ['app']